// SPDX-License-Identifier: LicenseRef-Nexartis-Proprietary
/**
 * SDK Version — GENERATED by scripts/gen-version.mjs. Do not edit by hand.
 *
 * Regenerated from package.json on every build / release. Kept committed so
 * bundlers and downstream consumers see a plain string constant.
 *
 * @module core/version
 */
export const SDK_VERSION = '1.2.5'; // x-release-please-version
