// SPDX-License-Identifier: Apache-2.0
/**
 * scripts/gen-version.mjs
 *
 * Single source of truth for SDK_VERSION: reads package.json `version` and
 * writes src/core/version.ts. Prevents the runtime/package drift that
 * shipped 1.2.2 hardcoded through the 1.3.0 release.
 *
 * Usage:
 *   node scripts/gen-version.mjs
 *
 * The generated file is committed (bundlers must see a plain constant), but
 * every `pnpm run build` / release step should re-run this script first.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const pkgPath = resolve(repoRoot, 'package.json');
const outPath = resolve(repoRoot, 'src/core/version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
if (typeof pkg.version !== 'string' || pkg.version.length === 0) {
	throw new Error(`gen-version: package.json is missing a valid "version" field (${pkgPath})`);
}

const body = `// SPDX-License-Identifier: Apache-2.0
/**
 * SDK Version — GENERATED by scripts/gen-version.mjs. Do not edit by hand.
 *
 * Regenerated from package.json on every build / release. Kept committed so
 * bundlers and downstream consumers see a plain string constant.
 *
 * @module core/version
 */
export const SDK_VERSION = '${pkg.version}'; // x-release-please-version
`;

writeFileSync(outPath, body, 'utf8');
console.log(`gen-version: wrote SDK_VERSION='${pkg.version}' → ${outPath}`);
